version: "3.8"
services:
  selenium-hub:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    restart: always

  python-selenium:
    build:
      context: .
    volumes:
      - ./app:/app
    command: "py.test -s -v"
    depends_on:
      - selenium-hub
